services:
  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: xray_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api
      - front
    networks:
      - xray_network
    restart: unless-stopped

  # PHP API
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: xray_api
    volumes:
      - ./api:/var/www/html
    networks:
      - xray_network
    # Connexion Ã  la DB externe (prod)
    environment:
      - MYSQL_HOST=109.176.199.253
      - MYSQL_DATABASE=xray_db
      - MYSQL_USER=xray_user
      - MYSQL_PASSWORD=Gn*uTl7M*1TzaV
    restart: unless-stopped

  # Next.js Frontend
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: xray_front
    networks:
      - xray_network
    environment:
      - NEXT_PUBLIC_API_URL=/api
    restart: unless-stopped

networks:
  xray_network:
    driver: bridge
